/* Schiller Institute — the conference archive, as data.
   One shared record set for the three /conferences/ archive treatments
   (gallery · firmament · playbill). In the WordPress build this file is
   replaced by a query loop over the `si_conference` CPT; the field shape
   below deliberately mirrors the CPT (title, dates, place, playlist).

   Sources: sessions/2026-07-16-consolidation-roadmap/02-youtube-channel-audit.md
   (playlist IDs are REAL — the Watch links work). Entries flagged `ph:true`
   carry titles/dates still to be confirmed during ingestion; `print:true`
   marks the pre-digital era. Order: newest first. */

window.SI_ERAS = [
  { key: "paradigm", name: "Toward the New Paradigm", range: "2024 — today",
    line: "The Global Majority takes the stage it was always promised. The newest rooms of the archive are still being hung." },
  { key: "reason", name: "The Age of Reason", range: "2022 — 2023",
    line: "Against the drums of war: emergency conferences convened at the speed of the crisis, with presidents and generals answering students." },
  { key: "online", name: "The World Online", range: "2020 — 2021",
    line: "The pandemic closed the halls — and the conference answered by becoming planetary. Six languages, every timezone, no ticket." },
  { key: "assembly", name: "The Assemblies", range: "2011 — 2019",
    line: "New York, Bad Soden, Paris: the camera learns to attend, one film per speech. The modern archive begins here." },
  { key: "print", name: "The Print Era", range: "1984 — 2010",
    line: "A quarter-century of proceedings that live in print and in memory. Digitization is on the roadmap; the gallery keeps their room lit." }
];

window.SI_CONFERENCES = [
  { y: 2026, when: "Date to be announced", title: "A Movement of World Citizens",
    place: "Online & in person", era: "paradigm", next: true,
    note: "Placeholder for the upcoming conference record — the seat this archive holds open is yours." },

  { y: 2025, when: "July 2025", title: "Man Is Not a Wolf to Man",
    place: "Berlin · & online", era: "paradigm", pl: "PLoHwt4KyUk5AQSojSSwzrmY0iiKsy-9SU",
    note: "Back in Berlin: strategy, development and a musical offering under one roof." },
  { y: 2025, when: "Memorial Day weekend, 2025", title: "A Beautiful Vision for Humanity",
    place: "Online, worldwide", era: "paradigm", pl: "PLoHwt4KyUk5CoOZjiQx8ZzJUx9crewBuB",
    note: "Two days composed against great turbulence — with per-speaker excerpt reels." },
  { y: 2024, when: "December 7–8, 2024", title: "In the Spirit of Schiller and Beethoven",
    place: "Online, worldwide", era: "paradigm", pl: "PLoHwt4KyUk5BuFCwNp09wFxSsuN1HZbrp",
    note: "The 40th-anniversary season closes the way every conference closes: with the chorus standing." },

  { y: 2023, when: "Autumn 2023", title: "The Strategic Situation After the Historic BRICS Summit",
    place: "Online, worldwide", era: "reason", pl: "PLoHwt4KyUk5A6e8qKmpq9qQfQhl938kpr",
    note: "Read the new world architecture while the ink was still wet." },
  { y: 2023, when: "September 9, 2023", title: "Let Us Join Hands with the Global Majority",
    place: "Online, worldwide", era: "reason", pl: "PLoHwt4KyUk5Cw0AyJkn5PjjWLC9_akeMK",
    note: "A former president, a Russian diplomat, an American priest — one panel, timestamped to the minute." },
  { y: 2023, when: "April 15–16, 2023", title: "Without the Development of All Nations, There Can Be No Lasting Peace",
    place: "Online, worldwide", era: "reason", pl: "PLoHwt4KyUk5DIAI7N5K8YvBmoEdKcvmSG",
    note: "The development argument, stated as a peace argument — the Institute's oldest theorem." },
  { y: 2023, when: "February 4, 2023", title: "The Age of Reason or the Annihilation of Humanity?",
    place: "Online, worldwide", era: "reason", pl: "PLoHwt4KyUk5Dffz7jVAihCnoXT2RCUBRs",
    note: "The question mark in the title is doing real work." },
  { y: 2023, when: "January 14, 2023", title: "Stop NATO's World War",
    place: "Online, worldwide", era: "reason", pl: "PLoHwt4KyUk5BI_QxL_lMYxjK-L9D6pwIf",
    note: "An emergency session, called the way one calls a fire brigade." },

  { y: 2022, when: "November 22, 2022", title: "Stop the Danger of Nuclear War Now",
    place: "Online, worldwide", era: "reason", pl: "PLoHwt4KyUk5D1_Z7Zi02Q9kn0Jf7HxdBO",
    note: "A single evening, one subject, no intermission." },
  { y: 2022, when: "September 10–11, 2022", title: "Inspiring Humanity to Survive the Greatest Crisis in World History",
    place: "Online, worldwide", era: "reason", pl: "PLoHwt4KyUk5DPZ02tyaNkMYYrfNE1VphU",
    note: "Four panels across two days; speakers from five continents, minuted to the second." },
  { y: 2022, when: "Mid-year, 2022", title: "There Can Be No Peace Without the Bankruptcy Reorganization of the Financial System",
    place: "Online, worldwide", era: "reason", pl: "PLoHwt4KyUk5DkW-buoxyXM6laxEB0lICI",
    note: "The longest title in the archive, and it still understates the argument." },
  { y: 2022, when: "April 9, 2022", title: "For a Conference to Establish a New Security and Development Architecture for All Nations",
    place: "Online, worldwide", era: "reason", pl: "PLoHwt4KyUk5ATvAWizEGiwjFxfmuPUOB1",
    note: "A conference convened to call for a conference — six weeks into the Ukraine war." },

  { y: 2021, when: "November 13–14, 2021", title: "Mankind Must Be the Immortal Species",
    place: "Online, worldwide", era: "online", pl: "PLoHwt4KyUk5AOO0AlzyiRtLNaJrWIvQjw",
    note: "Space science, pandemic policy and Beethoven's late quartets, treated as one subject." },
  { y: 2021, when: "June 26–27, 2021", title: "For the Common Good of All People, Not Rules Benefiting the Few", ph: true,
    place: "Online, worldwide", era: "online", pl: "PLoHwt4KyUk5AM0515zChBYV0dUgTKbyZQ",
    note: "Midsummer session of the online years — title to be confirmed at ingestion." },
  { y: 2021, when: "March 20–21, 2021", title: "The World at a Crossroad: Two Months into the New Administration",
    place: "Online, worldwide", era: "online", pl: "PLoHwt4KyUk5C3NYhozFTLmO4xjBhbr8SU",
    note: "A strategic inventory taken in public, sixty days into a new presidency." },
  { y: 2020, when: "December 12, 2020", title: "The World After the U.S. Election",
    place: "Online, worldwide", era: "online", pl: "PLoHwt4KyUk5AGynJ1XR-cp5ZMydgLtyZX",
    note: "Read the interregnum before it read us." },
  { y: 2020, when: "September 26, 2020", title: "The Youth Conference",
    place: "Online, worldwide", era: "online", pl: "PLoHwt4KyUk5Bs6Bvy1BfO4fDVTqdcccI2",
    note: "The rostrum handed, for a day, to the people who will have to finish the argument." },
  { y: 2020, when: "June 27, 2020", title: "Will Humanity Prosper, or Perish?",
    place: "Online, worldwide", era: "online", pl: "PLoHwt4KyUk5DWhMYHEidLO0zeIhq4uzfw",
    note: "An IMF director, a Russian counselor and a keynote that named the decade's choice." },
  { y: 2020, when: "April 25–26, 2020", title: "The First Online Conference",
    place: "Online, worldwide", era: "online", pl: "PLoHwt4KyUk5BLyjo-lYI1akY_m95R12QD",
    note: "Five weeks into lockdown, the hall went planetary — and never fully closed again." },

  { y: 2019, when: "November 16–17, 2019", title: "The Bad Soden Conference", ph: true,
    place: "Bad Soden, Germany", era: "assembly", pl: "PLoHwt4KyUk5DwvYfiV1GzQRoWSdQcxcg8",
    note: "The last of the old-style halls before the world moved online." },
  { y: 2019, when: "February 16, 2019", title: "Presidents' Day National Conference",
    place: "Morristown, New Jersey", era: "assembly", pl: "PLoHwt4KyUk5BkTXvZW6BQzXUop4HiJyrA",
    note: "A national conference on a national holiday, filmed talk by talk." },
  { y: 2018, when: "November 6, 2018", title: "The Paris Conference", ph: true,
    place: "Paris, France", era: "assembly", pl: "PLoHwt4KyUk5B2iUesv6EBeBrj6aDYdtbN",
    note: "The New Paradigm argued in French — title to be confirmed at ingestion." },
  { y: 2018, when: "September 13, 2018", title: "The New York City Conference", ph: true,
    place: "New York City", era: "assembly", pl: "PLoHwt4KyUk5AqCLdZY4emKBztbJdUfZvj",
    note: "One camera per speech — the archive's cleanest era." },
  { y: 2018, when: "June 30 – July 1, 2018", title: "The Bad Soden Midsummer Conference", ph: true,
    place: "Bad Soden, Germany", era: "assembly", pl: "PLoHwt4KyUk5AJ48ftO4TDRM1GLZ4YmAIe",
    note: "Two days on the Taunus slope — title to be confirmed at ingestion." },
  { y: 2018, when: "April 7, 2018", title: "A Dialogue of Three Presidencies",
    place: "Manhattan, New York", era: "assembly", pl: "PLoHwt4KyUk5Azhj6f0_f7M1o3W2o-et59",
    note: "Washington, Moscow, Beijing — treated as one conversation, in one room." },
  { y: 2017, when: "November 25–26, 2017", title: "Fulfilling the Dream of Mankind",
    place: "Bad Soden, Germany", era: "assembly", pl: "PLoHwt4KyUk5Diy9gwbA5IL5J4q6SRtEhC",
    note: "The New Silk Road becomes the World Land-Bridge — the flagship argument, in full." },
  { y: 2017, when: "April 13–14, 2017", title: "The New York Conference", ph: true,
    place: "New York City", era: "assembly", pl: "PLoHwt4KyUk5CfL_UCuxSmmr0hyQNZlZjL",
    note: "Two spring days in Manhattan — title to be confirmed at ingestion." },
  { y: 2016, when: "June 25–26, 2016", title: "The Berlin Conference", ph: true,
    place: "Berlin, Germany", era: "assembly",
    note: "Reel being restored from the channel's legacy playlists." },
  { y: 2016, when: "September 2016", title: "Living Memorial — the September 11 Concerts", ph: true,
    place: "New York City", era: "assembly",
    note: "The Mozart Requiem sung across the boroughs — the conference method, in pure music." },
  { y: 2015, when: "2013 – 2015", title: "The Touring Years", ph: true,
    place: "Frankfurt · Los Angeles · Virginia · New York · New England", era: "assembly",
    note: "Five regional conferences being catalogued from the channel's legacy playlists." },
  { y: 2012, when: "2011 – 2012", title: "The Legacy Panels", ph: true,
    place: "Various", era: "assembly",
    note: "The channel's earliest conference recordings — single panels, being restored to full records." },

  { y: 2010, yl: "1984–2010", when: "1984 – 2010", title: "A Quarter-Century in Print", print: true,
    place: "Wiesbaden · Washington · worldwide", era: "print",
    note: "Hundreds of panels preserved in printed proceedings and journals. Digitization queued — this room of the gallery is reserved." },
  { y: 1984, when: "1984", title: "The Founding Conferences", print: true,
    place: "Germany & the United States", era: "print",
    note: "The year the Institute resolved that statecraft and Schiller belong on one stage. Proceedings in print." }
];
