#!/usr/bin/env python3
"""
day1-merge-segauto.py — incorporate the other session's deterministic video presort
(sessions/2026-07-16-consolidation-roadmap/work/seg-auto.jsonl) into our
incoming/video-segmentation.csv.

Merge policy (documented in 00-README):
  - OUR rows from priority sources (wp-era-b, desc regexes, per-talk-video, case-5 agendas)
    are NEVER overridden — their presort only fills gaps.
  - Rows where WE are case 4 (no signal) and THEY resolved the video:
      * their case 3 kind=Talk    → upgrade to case 3 talk with presenter/title parsed
      * their case 3 kind=Excerpt → keep case 3 but final_action=skip (07 §4: excerpts attach
        to the parent presentation, never become their own record)
      * their case 4 (long panel) → stays full_session; note agreement (confidence up)
      * their case 1/2/5          → adopt marks/agenda (rare)
  - Videos they have that we don't carry at all (playlist classified differently) → counted, skipped.

Usage: day1-merge-segauto.py <seg-auto.jsonl> <video-segmentation.csv> <person-map.csv>
"""
import sys, json, csv, re, unicodedata, collections

SEG_AUTO, SEG_CSV, PERSON_CSV = sys.argv[1], sys.argv[2], sys.argv[3]

HONORIFICS = ['h.e.', 'h. e.', 'hon.', 'dr.', 'dr', 'prof.', 'prof', 'professor', 'sen.', 'senator',
    'amb.', 'ambassador', 'col.', 'colonel', 'oberst', 'gen.', 'general', 'rev.', 'father', 'pater',
    'mr.', 'mrs.', 'ms.', 'rep.', 'lt. col.', 'brigadier']

def fold(s):
    s = unicodedata.normalize('NFKD', s)
    return ''.join(c for c in s if not unicodedata.combining(c)).lower().strip()

def person_key(raw):
    s = re.sub(r'\([^)]*\)', ' ', raw or '')
    s = re.sub(r'["“”«„].*', ' ', s).strip(' \t,:;–—-')
    f = fold(s)
    changed = True
    while changed:
        changed = False
        for h in HONORIFICS:
            if f.startswith(h + ' '):
                f = f[len(h):].strip(); changed = True
    return re.sub(r'[^\w]+', '-', f, flags=re.UNICODE).strip('-')

theirs = {}
for line in open(SEG_AUTO, encoding='utf-8'):
    rec = json.loads(line)
    theirs[rec['video_id']] = rec

rows = list(csv.DictReader(open(SEG_CSV, encoding='utf-8')))
by_vid = collections.defaultdict(list)
for r in rows:
    by_vid[r['yt_video_id']].append(r)

stats = collections.Counter()
new_person_keys = {}

for vid, rec in theirs.items():
    ours = by_vid.get(vid)
    if not ours:
        stats['their_video_not_in_our_scope'] += 1
        continue
    mine = ours[0]
    if len(ours) > 1 or mine['case'] not in ('4',):
        # we already resolved it from a priority source — count agreement/disagreement only
        stats['ours_already_resolved'] += 1
        continue
    tcase = rec['case']
    pres = rec.get('presentations') or []
    if tcase == 3 and pres:
        p = pres[0]
        kind = (p.get('kind') or 'Talk').lower()
        name = (p.get('presenter') or '').strip()
        key = person_key(name) if name else ''
        mine['case'] = '3'
        mine['kind'] = 'talk'
        mine['start_seconds'] = str(p.get('start_seconds') or 0)
        mine['end_seconds'] = str(p.get('end_seconds') or rec.get('duration') or '')
        if name:
            mine['speaker_raw'] = name
            mine['person_key'] = key
            if len(key) >= 3:
                new_person_keys.setdefault(key, name)
        mine['affiliation'] = p.get('presenter_affiliation') or ''
        tt = (p.get('title') or '').strip(' "”“')
        if tt and fold(tt) != fold(rec['video_title']):
            mine['talk_title'] = tt
            mine['title_autogenerated'] = '0'
        elif name:
            mine['title_autogenerated'] = '1'
        mine['source'] = 'per-talk-video'
        mine['reviewer'] = 'fable-day1'
        if kind == 'excerpt':
            mine['final_action'] = 'skip'
            mine['needs_review'] = '0'
            mine['notes'] = 'excerpt clip — attach to parent presentation (07 §4); merged from work/seg-auto'
            stats['upgraded_excerpt_skip'] += 1
        else:
            mine['final_action'] = ''
            mine['needs_review'] = '0' if name else '1'
            mine['notes'] = 'per-talk record merged from work/seg-auto presort'
            stats['upgraded_per_talk'] += 1
    elif tcase == 4:
        mine['notes'] = (mine['notes'] + '; ' if mine['notes'] else '') + 'presort agrees: long-panel full session'
        mine['needs_review'] = '0'
        mine['reviewer'] = 'fable-day1'
        stats['case4_confirmed_full_session'] += 1
    elif tcase == 5 and pres:
        ag = pres[0].get('agenda') or []
        if ag and not mine['agenda_json']:
            mine['agenda_json'] = json.dumps([
                {'speaker_raw': a if isinstance(a, str) else a.get('label', ''),
                 'person_key': person_key(a if isinstance(a, str) else a.get('label', '')),
                 'affiliation': '', 'country': '', 'talk_title': ''} for a in ag], ensure_ascii=False)
            mine['case'] = '5'
            mine['kind'] = 'full_session'
            mine['upgrade_candidate'] = '1'
            mine['notes'] = 'agenda merged from work/seg-auto presort'
            mine['reviewer'] = 'fable-day1'
            stats['case5_agenda_adopted'] += 1
    elif tcase in (1, 2) and pres:
        stats['case12_available_not_auto_merged'] += 1   # rare; flag for manual look
        mine['notes'] = (mine['notes'] + '; ' if mine['notes'] else '') + f'presort has case-{tcase} marks — see work/seg-auto.jsonl'
    else:
        stats['no_action'] += 1

with open(SEG_CSV, 'w', newline='', encoding='utf-8') as f:
    w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
    w.writeheader(); w.writerows(rows)

# reconcile any new person keys
pm = list(csv.DictReader(open(PERSON_CSV, encoding='utf-8')))
known = set()
for r in pm:
    known.add(r['person_key'])
    if r['final_action'].startswith('merge:'):
        known.add(r['final_action'][6:])
added = 0
for k, raw in sorted(new_person_keys.items()):
    if k in known:
        continue
    pm.append({'person_key': k, 'canonical_name': raw, 'honorific': '', 'affiliation': '',
        'country': '', 'person_type': 'speaker', 'aliases': raw, 'source_refs': 'seg-auto-merge',
        'occurrences': '1', 'needs_review': '1', 'notes': 'added via seg-auto presort merge',
        'final_action': '', 'reviewer': ''})
    added += 1
with open(PERSON_CSV, 'w', newline='', encoding='utf-8') as f:
    w = csv.DictWriter(f, fieldnames=list(pm[0].keys()))
    w.writeheader(); w.writerows(pm)

case_hist = collections.Counter(r['case'] for r in rows)
review = sum(1 for r in rows if r['needs_review'] == '1' and not r['final_action'])
print('merge stats:', dict(stats))
print('new case histogram:', dict(sorted(case_hist.items())))
print(f'rows still needing review: {review}; new person keys added: {added}')
