<?php
/**
 * day1-scan.php — pipeline stage D standalone (no WP): per-video source resolution +
 * 5-case sort → video-segmentation.csv. Reuses the unit-tested parser classes from
 * si-migrate.php (SI_Text, SI_Parse, SI_Person_Key — WP_CLI-independent by design).
 *
 * Usage: php day1-scan.php <yt-dump-dir> <conference-map.csv> <era-b.json> <person-map.csv> <out.csv>
 */
declare(strict_types=1);
require __DIR__ . '/../mu-plugins/si-migrate.php';

[$self, $dir, $conf_csv, $erab_json, $person_csv, $out] = $argv + [null, null, null, null, null, null];
$dir = rtrim($dir, '/');

$confs = SI_Csv::read($conf_csv);
$era_b = json_decode(file_get_contents($erab_json), true) ?: [];
$person_index = [];
foreach (SI_Csv::read($person_csv) as $pr) { $person_index[$pr['person_key']] = true; }

$rows = [];
$stats = ['videos' => 0, 'no_meta' => 0, 'dupe_video' => 0];
$case_hist = [];
$missing = [];
$seen = [];

function seg_row(string $vid, int $seg, string $plid, string $ckey, int $case, string $kind,
    $start, $end, string $raw, string $name, string $country, string $affil, string $talk,
    string $source, string $upgrade, string $note, string $agenda_json = '', string $chapters_json = ''): array {
    $pkey = $name !== '' ? SI_Person_Key::key($name) : '';
    $needs_review = ($case === 1 && $pkey === '') || $case === 4 || $note !== '' ? '1'
        : (in_array($source, ['wp-era-b', 'per-talk-video'], true) ? '0' : '1');
    return [
        'yt_video_id' => $vid, 'segment_index' => $seg, 'playlist_id' => $plid, 'conference_key' => $ckey,
        'panel_title' => '', 'case' => $case, 'kind' => $kind,
        'start_seconds' => $start, 'end_seconds' => $end,
        'speaker_raw' => $raw, 'person_key' => $pkey, 'country' => $country, 'affiliation' => $affil,
        'talk_title' => $talk, 'title_autogenerated' => $talk === '' && $name !== '' ? '1' : '0',
        'agenda_json' => $agenda_json, 'chapters_json' => $chapters_json,
        'source' => $source, 'upgrade_candidate' => $upgrade, 'needs_review' => $needs_review,
        'notes' => $note, 'final_action' => '', 'reviewer' => '',
    ];
}

foreach ($confs as $conf) {
    $plid = $conf['yt_playlist_id'];
    if ($plid === '') { continue; }
    $pl_file = "$dir/playlist-$plid.txt";
    if (!is_readable($pl_file)) { continue; }
    foreach (array_filter(array_map('trim', file($pl_file))) as $vline) {
        [$vid, $vtitle, $vdur] = array_pad(explode('|', $vline, 3), 3, '');
        if (strlen($vid) !== 11) { continue; }
        $stats['videos']++;
        $meta = json_decode(@file_get_contents("$dir/videos/$vid.json") ?: 'null', true) ?: [];
        if (!$meta) { $stats['no_meta']++; $missing[] = $vid; continue; }   // dump incomplete — rescan later
        if (isset($seen[$vid])) { $stats['dupe_video']++; continue; }        // multi-playlist video: first conference wins
        $seen[$vid] = true;
        $desc = (string) ($meta['description'] ?? '');
        $duration = (int) ($meta['duration'] ?? (float) $vdur);
        $chapters = $meta['chapters'] ?? [];

        $marks = $era_b[$vid] ?? [];
        $source = $marks ? 'wp-era-b' : 'none';
        if (!$marks) {
            $marks = SI_Parse::desc_leading($desc);
            if (count($marks) >= 2) { $source = 'yt-desc-leading'; }
            else {
                $marks = SI_Parse::desc_trailing($desc);
                if (count($marks) >= 2) { $source = 'yt-desc-trailing'; }
                else { $marks = []; }
            }
        }
        if (!$marks && $chapters && (SI_Parse::desc_leading($desc) || SI_Parse::desc_trailing($desc))) {
            $marks = array_map(static fn($c) => ['t' => (int) $c['start_time'], 'label' => $c['title'] ?? ''], $chapters);
            $source = 'yt-chapters';
        }
        $agenda = SI_Parse::agenda_lines($desc);
        $single = (bool) preg_match('/^[^:]{3,60}:\s+\S/', SI_Text::normalize($vtitle)) && $duration > 0 && $duration < 3600;
        $sort = SI_Parse::case_sort($marks, $agenda, $duration, $person_index, $single);
        $case = $sort['case'];
        $case_hist[$case] = ($case_hist[$case] ?? 0) + 1;

        if ($case === 1) {
            [$ok, ] = SI_Parse::validate_marks($marks, $duration);
            $seg = 0;
            foreach ($marks as $j => $mk) {
                $label = $mk['label'];
                $is_name = SI_Parse::name_score($label, $person_index) >= 0.5;
                $end = isset($marks[$j + 1]) ? $marks[$j + 1]['t'] - 1 : ($duration ?: '');
                $talk_title = '';
                if (preg_match('/["“](.+?)["”]/u', ($mk['tail'] ?? '') . ' ' . $label, $tm)) { $talk_title = $tm[1]; }
                $name = $mk['name'] ?? ($is_name ? trim(explode(',', preg_replace('/\([^)]*\)/', '', $label))[0]) : '');
                $rows[] = seg_row($vid, $seg++, $plid, $conf['conference_key'], $case, $is_name ? 'talk' : 'chaptered',
                    $mk['t'], $end, $label, (string) $name, $mk['country'] ?? '', trim(explode(':', $mk['tail'] ?? '')[0] ?? ''),
                    $talk_title, $source, '0', $ok ? '' : $sort['reason']);
            }
        } elseif ($case === 2) {
            $chap_json = json_encode(array_map(static fn($m) => ['label' => $m['label'], 'start_seconds' => $m['t']], $marks), JSON_UNESCAPED_UNICODE);
            $rows[] = seg_row($vid, 0, $plid, $conf['conference_key'], 2, 'chaptered', '', '',
                $vtitle, '', '', '', $vtitle, $source, '0', $sort['reason'], '', $chap_json);
        } elseif ($case === 3) {
            [$name, $talk] = array_pad(explode(':', SI_Text::normalize($vtitle), 2), 2, '');
            $rows[] = seg_row($vid, 0, $plid, $conf['conference_key'], 3, 'talk', '', '',
                $vtitle, trim($name), '', '', trim($talk), 'per-talk-video', '0', $sort['reason']);
        } else {
            $agenda_json = $agenda ? json_encode(array_map(static function ($line) {
                $name = trim(explode(',', preg_replace('/\([^)]*\)|["“”].*/u', '', $line))[0]);
                $talk = preg_match('/["“](.+?)["”]/u', $line, $m) ? $m[1] : '';
                return ['speaker_raw' => $line, 'person_key' => SI_Person_Key::key($name),
                    'affiliation' => '', 'country' => '', 'talk_title' => $talk];
            }, $agenda), JSON_UNESCAPED_UNICODE) : '';
            $rows[] = seg_row($vid, 0, $plid, $conf['conference_key'], $case, 'full_session', '', '',
                $vtitle, '', '', '', $vtitle, $source === 'none' ? 'none' : $source,
                $case === 5 ? '1' : '0', $sort['reason'], $agenda_json);
        }
    }
}

SI_Csv::write($out, $rows, array_keys($rows[0]));
if ($missing) { file_put_contents(dirname($out) . '/scan-missing-videos.txt', implode("\n", $missing) . "\n"); }
ksort($case_hist);
$src_hist = array_count_values(array_column($rows, 'source'));
fwrite(STDERR, sprintf("videos scanned: %d (skipped, no meta yet: %d; dupes: %d)\nsegment rows: %d -> %s\ncase histogram: %s\nsources: %s\n",
    $stats['videos'], $stats['no_meta'], $stats['dupe_video'], count($rows), $out,
    json_encode($case_hist), json_encode($src_hist)));
