#!/usr/bin/env python3
"""
day2-class-worklist.py — generate the review worklist for classification.csv (File 4).

File 4 is a spot-check, not a review: every flagged row already carries a final_type, so
nothing here is silently dropped. Three filtered slices need human eyes, plus a short
fourth list of rows whose final_type sits outside the guide's vocabulary.

Each row is rendered with its live URL so the check is "open, read, confirm".

Usage: python3 day2-class-worklist.py [--dir incoming] [--out <path>] [--base URL]
"""
import argparse
import collections
import csv
import os
import re

STD_TYPES = {'post', 'si_video', 'si_presentation', 'si_conference', 'si_statement',
             'si_coverage', 'si_document', 'retire'}


def effective(r):
    """What this row actually becomes: final_type, else the proposal if unflagged."""
    f = (r['final_type'] or '').strip()
    if f:
        return f
    return (r['proposed_type'] or '').strip() if r['needs_review'] == '0' else None

# --normalize-domains resolves every legacy host to this one (00-README.md:56)
BASE = 'https://schillerinstitute.com'

# Title shapes that argue for si_statement — the Institute speaking as an organization.
STATEMENT_WORDS = re.compile(
    r'\b(press\s*release|release:|presseerkl|erkl[äa]rung|appeal|appell|petition|'
    r'resolution|resolutione?|open letter|offener brief|call for|aufruf|urgent call|'
    r'demand|declaration|memorandum|communiqu)', re.I)
# Title shapes that argue for an ordinary report about something.
REPORT_WORDS = re.compile(
    r'\b(report|bericht|conference|konferenz|interview|seminar|webcast|panel|'
    r'endorse|receives|honou?rs|celebrat|announces|releases video)', re.I)


def signal(title):
    s, r = bool(STATEMENT_WORDS.search(title or '')), bool(REPORT_WORDS.search(title or ''))
    if s and not r:
        return 'title reads **statement**'
    if r and not s:
        return 'title reads **report**'
    if s and r:
        return 'title carries both signals'
    return 'title is neutral — the body decides'


def url(r, base):
    u = (r['legacy_url'] or '').strip()
    if not u or u.startswith('/?'):
        return ''                      # ?p=123 / ?page_id=123 — no readable permalink
    return base.rstrip('/') + u


def row_line(r, ln, base, show_type=True):
    u = url(r, base)
    link = f"[{r['legacy_id']}]({u})" if u else f"`{r['legacy_id']}` (no permalink)"
    title = (r['title'] or '').strip() or '*(empty title)*'
    head = f"- **L{ln}** {link} · `{r['language']}`"
    if show_type:
        head += f" · currently **{r['final_type'] or '—'}**"
    return f"{head}  \n  {title}  "


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--dir', default='incoming')
    ap.add_argument('--out', default=None)
    ap.add_argument('--base', default=BASE)
    args = ap.parse_args()

    path = os.path.join(args.dir, 'classification.csv')
    rows = list(csv.DictReader(open(path, encoding='utf-8')))
    ln = {id(r): i + 2 for i, r in enumerate(rows)}
    base = args.base

    verify = [r for r in rows if 'verify' in (r['notes'] or '').lower()]
    retire_pub = [r for r in rows
                  if r['final_type'] == 'retire' and r['post_status'] == 'publish']
    retire_other = [r for r in rows
                    if r['final_type'] == 'retire' and r['post_status'] != 'publish']
    dash = [r for r in rows if (r['final_topics'] or '').strip() == '-']
    odd = [r for r in rows if (r['final_type'] or '').strip()
           and r['final_type'] not in STD_TYPES]

    # WPML translation groups whose members would become different things
    bytrid = collections.defaultdict(list)
    for r in rows:
        if (r['trid'] or '').strip():
            bytrid[r['trid']].append(r)
    split = [g for g in bytrid.values()
             if len(g) > 1 and len({effective(r) for r in g if effective(r)}) > 1]

    L = []
    w = L.append
    w("# classification.csv — Review Worklist (File 4)")
    w("")
    w(f"Auto-generated by `tools/day2-class-worklist.py` from {len(rows)} rows. "
      "**An aid, not an authority.**")
    w("")
    w("**This file is a spot-check, not a review.** All 303 flagged rows already carry a "
      "`final_type`, so — unlike File 3 — nothing here is silently dropped if you stop halfway. "
      "Blank `final_type` on an unflagged row means \"accept the proposal\".")
    w("")
    w("Edit only: **T** `final_type` · **U** `final_topics` · **S** `notes` · **V** `reviewer`. "
      "Put your initials in `reviewer` on every row you touch, including ones you confirm "
      "unchanged — that is how we tell \"checked, correct\" from \"never looked at\".")
    w("")
    w("| Slice | Rows | Question |")
    w("|---|---:|---|")
    w(f"| 1 | {len(verify)} | is this an Institute *statement* or an ordinary *report*? |")
    w(f"| 2 | {len(retire_pub)} | is anything published being wrongly unpublished? |")
    w(f"| 3 | {len(dash)} | does a topic actually jump out? |")
    w(f"| 4 | {len(odd)} | non-standard `final_type` — confirm deliberate |")
    w(f"| 5 | {len(split)} | translation siblings that become different things |")
    w(f"| | **{len(verify) + len(retire_pub) + len(dash) + len(odd) + len(split)}** | |")
    w("")

    # ---- slice 1
    w("---")
    w("")
    w(f"## 1. `notes` contains \"verify\" — statement vs report ({len(verify)})")
    w("")
    w("All published. 84 of these come from one rule (**R6**, the `activity-initiatives` "
      "category), which swept in both Institute statements and ordinary event reports. "
      "The machine split them 49 `post` / 34 `si_statement` at low confidence — your job is to "
      "confirm or flip each one.")
    w("")
    w("**The test:** does the page *say something as the Schiller Institute* — an appeal, open "
      "letter, petition, resolution, press release, usually with a signature block or a call to "
      "act? That is `si_statement`. Does it *describe something that happened* — a conference "
      "took place, someone endorsed something, an award was received? That is `post`. When the "
      "body is a report **about** a statement, it is a `post`.")
    w("")
    w("The **signal** line is a keyword read of the title only. It is a hint, not a verdict — "
      "the body decides.")
    w("")
    for grp, label in ((('post',), 'currently `post` — flip to `si_statement` if it speaks *as* the Institute'),
                       (('si_statement',), 'currently `si_statement` — flip to `post` if it merely reports'),
                       (None, 'other current types')):
        sub = ([r for r in verify if r['final_type'] in grp] if grp
               else [r for r in verify if r['final_type'] not in ('post', 'si_statement')])
        if not sub:
            continue
        w(f"### {label} ({len(sub)})")
        w("")
        for r in sub:
            w(row_line(r, ln[id(r)], base, show_type=False))
            w(f"  _{signal(r['title'])}_  ")
        w("")

    # ---- slice 2
    w("---")
    w("")
    w(f"## 2. `final_type` = retire ({len(retire_pub)} published + {len(retire_other)} not)")
    w("")
    w("Retire means **unpublished, not deleted** — the row stays in the database and can be "
      "restored. Only the published ones are a real risk, because those are the pages the public "
      "can see today.")
    w("")
    w(f"### 2a · published — read every one ({len(retire_pub)})")
    w("")
    for r in retire_pub:
        w(row_line(r, ln[id(r)], base, show_type=False))
        w(f"  _{(r['notes'] or '').strip()[:110]}_  ")
    w("")
    w(f"### 2b · already draft/private ({len(retire_other)}) — skim only")
    w("")
    w("These are invisible on the live site either way, so retiring them changes nothing. "
      "Two are flagged KEEP-CANDIDATE and need a real decision — see slice 4.")
    w("")

    # ---- slice 3
    w("---")
    w("")
    w(f"## 3. `final_topics` = \"-\" — genuinely topic-less ({len(dash)})")
    w("")
    w("`-` means \"reviewed: deliberately none\", which is a legitimate final answer. Assign a "
      "topic only if one jumps out; most of these are invitations, announcements, condolences and "
      "award notices that genuinely have no subject matter. Replace the `-` in **U** only when "
      "you are confident.")
    w("")
    w("Slugs: `peace-strategy` · `physical-economy` · `great-projects` · `classical-culture` · "
      "`science-space` · `health-food` · `energy-environment` · `education-youth` · "
      "`history-method` · `new-paradigm` (two max, separated by `|`).")
    w("")
    for r in dash:
        w(row_line(r, ln[id(r)], base))
    w("")

    # ---- slice 4
    w("---")
    w("")
    w(f"## 4. Non-standard `final_type` ({len(odd)}) — confirm these are deliberate")
    w("")
    w("These sit outside the eight types in the guide's table. They look intentional; confirm and "
      "initial, or change to a standard type.")
    w("")
    for r in odd:
        w(row_line(r, ln[id(r)], base))
        w(f"  status `{r['post_status']}` · _{(r['notes'] or '').strip()[:110]}_  ")
    w("")

    # ---- slice 5
    w("---")
    w("")
    w(f"## 5. Translation groups that split ({len(split)})")
    w("")
    w("Rows sharing a `trid` are the same article in different languages, so they should "
      "normally become the same thing. All the splits below involve `retire`, which is often "
      "legitimate — retiring an empty-title or draft duplicate in one language while keeping the "
      "others. Confirm each is deliberate.")
    w("")
    for g in sorted(split, key=lambda g: int(g[0]['trid'] or 0)):
        kinds = sorted({effective(r) or '?' for r in g})
        w(f"- **trid {g[0]['trid']}** — {' vs '.join(kinds)}  ")
        for r in g:
            u = url(r, base)
            t = (r['title'] or '').strip() or '*(empty title)*'
            link = f"[{r['legacy_id']}]({u})" if u else f"`{r['legacy_id']}`"
            w(f"    - L{ln[id(r)]} `{r['language']}` **{effective(r) or '?'}** "
              f"({r['post_status']}) {link} — {t[:60]}  ")
    w("")

    out = args.out or os.path.join(os.path.dirname(args.dir) or '.',
                                   'classification-review-worklist.md')
    with open(out, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(L) + '\n')
    print(f"wrote {out}")
    print(f"  slice 1 verify        {len(verify):4d}")
    print(f"  slice 2 retire (pub)  {len(retire_pub):4d}  (+{len(retire_other)} draft/private)")
    print(f"  slice 3 topic-less    {len(dash):4d}")
    print(f"  slice 4 odd type      {len(odd):4d}")
    print(f"  slice 5 split trids   {len(split):4d}")


if __name__ == '__main__':
    main()
